theme = "nord-dark"
icons = "material-nf"

[[block]]
block = "disk_space"
path = "/mnt"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "/ {available}"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "/home {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "RAM {mem_used_percents}"

[[block]]
block = "cpu"
format = "CPU {utilization}"

[[block]]
interval = 5

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "uptime"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
