[theme]
theme = "nord-dark"

[icons]
icons = "material-nf"

# Commented out because the use of single partition
#[[block]]
#block = "disk_space"
#path = "/"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = " $icon root: $available.eng(w:2) "

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:30) |"

#[[block]]
#block = "music"
#player = "spotify"
#[[block.click]]
#button = "left"
#action = "play_pause"
#[[block.click]]
#button = "up"
#action = "volume_up"
#[[block.click]]
#button = "down"
#action = "volume_down"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon home: $available.eng(w:2) "

[[block]]
block = "cpu"
format = " $icon $utilization $frequency "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) " 

[[block]]
block = "temperature"
format = " $icon $average avg "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
format = " $icon { $volume|} "
natural_mapping = true
headphones_indicator = true

[[block]]
block = "battery"
driver = "upower"
format = " $icon $percentage $time "

[[block]]
block = "uptime"
interval = 1

[[block]]
block = "time"
interval = 1
[block.format]
short = " $icon $timestamp.datetime(f:%R) "
